name: Check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Perform checks
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv lock --dev --requirements > requirements.txt
        pipenv install --dev
        pipenv run lint
        pipenv run type-check
