name: Check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Perform checks
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        flake8 pika-stubs
        mypy -p pika-stubs --strict
